SELECT ?author ?authorLabel ?birthDate ?birthPlace ?birthPlaceLabel 
WHERE {
  ?author wdt:P31 wd:Q5;          # human
          wdt:P27 wd:Q142;        # nationality France
          wdt:P106 wd:Q36180;     # writer
          wdt:P569 ?birthDate;    # date of birth
          wdt:P19 ?birthPlace.    # place of birth

  SERVICE wikibase:label { bd:serviceParam wikibase:language "fr,en". }
}
LIMIT 500

